# Generated by Django 2.1.2 on 2018-11-05 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20181031_1556'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relationship',
            name='follower',
        ),
        migrations.RemoveField(
            model_name='relationship',
            name='owner',
        ),
        migrations.DeleteModel(
            name='Relationship',
        ),
    ]
