# Generated by Django 2.1.2 on 2018-11-01 03:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_original_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='original_avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/%y/%m/%d', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'gif'])]),
        ),
    ]
