# Generated by Django 2.1.2 on 2018-11-01 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20181101_0320'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='test_field',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
