# Generated by Django 2.1.2 on 2018-11-01 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_test_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='test_field',
        ),
    ]
