# Generated by Django 2.1.2 on 2018-11-01 04:22

import django.core.validators
from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_user_test_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='original_avatar',
        ),
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='avatars/%y/%m/%d', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'gif'])]),
        ),
    ]
